title: Training
author: Me 
email: nottelling@you.com
description: > # this means to ignore newlines until "baseurl:"
Stuff

# social links
twitter_username: nope
github_username:  nope

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
